Olx_hardware_store/accounts/urls.py
from django.urls import path, include
from .views import RegisterUserView, LoginUserView, LogoutUserView, DetailsProfileView, EditProfileView,\
    DeleteProfileView, add_phone_numbers, ForbiddenView

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register_user'),
    path('login/', LoginUserView.as_view(), name='login_user'),
    path('logout/', LogoutUserView.as_view(), name='logout_user'),
    path('profile/<int:pk>/', include([
        path('', DetailsProfileView.as_view(), name='details_profile'),
        path('edit/', EditProfileView.as_view(), name='edit_profile'),
        path('delete/', DeleteProfileView.as_view(), name='delete_profile'),
        path('contacts/', include([
            path('', add_phone_numbers, name='contacts_profile')
        ]))
    ])),
    path('403/', ForbiddenView.as_view(), name='forbidden')
]

# admin user juli21
# password for all users 123$QWEr

Olx_hardware_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Olx_hardware_store.common.urls')),
    path('accounts/', include('Olx_hardware_store.accounts.urls')),
    path('tools/', include('Olx_hardware_store.tools.urls'))
]

Olx_hardware_store/accounts/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify
from .validators import validate_isalpha, validate_phone_number
from datetime import datetime


class HwStoreUser(auth_models.AbstractUser):
    FIRST_NAME_MIN_LENGTH = 2
    FIRST_NAME_MAX_LENGTH = 30
    LAST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 30

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        validators=[MinLengthValidator(FIRST_NAME_MIN_LENGTH), validate_isalpha],
        null=False,
        blank=False
    )

    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        validators=[MinLengthValidator(LAST_NAME_MIN_LENGTH), validate_isalpha],
        null=False,
        blank=False
    )

    email = models.EmailField(
        unique=True,
        null=False,
        blank=False
    )

    profile_bio = models.TextField(
        null=True,
        blank=True
    )

    created_on = models.DateTimeField(
        auto_now_add=datetime.now()
    )


class PhoneNumbersUserModel(models.Model):
    phone = models.CharField(
        max_length=13,
        default=None,
        validators=[validate_phone_number, ]
    )

    user = models.ForeignKey(
        HwStoreUser,
        on_delete=models.CASCADE
    )

    slug = models.SlugField(unique=True, null=True, blank=True)

    USERNAME_FIELD = 'slug'
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f"{self.phone}-{self.id}")
        return super().save(*args, **kwargs)

Olx_hardware_store/tools/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from Olx_hardware_store.settings import AUTH_USER_MODEL
from datetime import datetime

UserModel = get_user_model()


class Tool(models.Model):
    name = models.CharField(
        max_length=50
    )

    tool_photo = models.URLField()

    description = models.TextField(
        max_length=200
    )

    tool_country = models.CharField(
        max_length=30
    )

    tool_city = models.CharField(
        max_length=50
    )

    tool_price = models.DecimalField(
        max_digits=6,
        decimal_places=2
    )

    created_on = models.DateTimeField(
        auto_now_add=datetime.now()
    )

    last_edit = models.DateTimeField(
        auto_now=datetime.now()
    )

    slug = models.SlugField(
        unique=True,
        null=True,
        blank=True
    )

    USERNAME_FIELD = 'slug'
    REQUIRED_FIELDS = []

    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True, null=True
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.id}")
        return super().save(*args, **kwargs)

Olx_hardware_store/accounts/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import HwStoreUser, PhoneNumbersUserModel


class RegisterUserForm(auth_forms.UserCreationForm):
    class Meta:
        model = HwStoreUser
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )

    password2 = forms.CharField(
        label=_("Repeat password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = _('')
        self.fields['username'].help_text = _('')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = HwStoreUser
        fields = ['first_name', 'last_name', 'profile_bio', ]


class PhoneNumbersUserForm(forms.ModelForm):
    class Meta:
        model = PhoneNumbersUserModel
        fields = ['phone', ]

Olx_hardware_store/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic as views
from .forms import RegisterUserForm, EditProfileForm, PhoneNumbersUserForm
from .models import HwStoreUser
from Olx_hardware_store.permissions import AuthUserPermissions


class ForbiddenView(views.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'perm_denied.html', status=403)


class RegisterUserView(views.CreateView):
    template_name = 'accounts/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main_page')

    def form_valid(self, form):
        result = super().form_valid(form)
        login(self.request, self.object)
        return result


class LoginUserView(auth_views.LoginView):
    template_name = 'accounts/login.html'


class LogoutUserView(auth_views.LogoutView):
    pass


class DetailsProfileView(views.DetailView):
    model = HwStoreUser
    template_name = 'accounts/profile/details_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['tools'] = self.request.user.tool_set.all()
        return context


class EditProfileView(AuthUserPermissions, views.UpdateView):
    model = HwStoreUser
    form_class = EditProfileForm
    template_name = 'accounts/profile/edit_profile.html'

    def get_success_url(self):
        profileid = self.kwargs['pk']
        return reverse_lazy('details_profile', kwargs={'pk': profileid})

    def get_object(self, queryset=None):
        return self.request.user


class DeleteProfileView(AuthUserPermissions, views.DeleteView):
    model = HwStoreUser
    template_name = 'accounts/profile/delete_profile.html'
    success_url = reverse_lazy('register_user')


@login_required
def add_phone_numbers(request, pk):
    form = PhoneNumbersUserForm()

    if request.method == 'POST':
        form = PhoneNumbersUserForm(request.POST)
        if form.is_valid():
            phone = form.save(commit=False)
            phone.user = request.user
            phone.save()

            return redirect('details_profile', pk=request.user.pk)

    context = {
        "form": form,
    }

    return render(request, 'accounts/profile/contacts_profile.html', context=context)

templates/accounts/profile/contacts_profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Contacts</h1>

<form action="{% url 'contacts_profile' user.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
</form>

</body>
</html>

templates/accounts/profile/delete_profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Profile delete</h1>

<form action="{% url 'delete_profile' object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <h1>
        Are you sure you want to delete your profile?
        Any changes are irreversible.
    </h1>

    <button>Delete profile</button>
</form>

</body>
</html>

templates/accounts/profile/details_profile.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block content %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/styles/pic_size.css">
    <title>Document</title>
</head>
<body>

<h1>Profile details</h1>

<form action="{% url 'details_profile' pk=object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <div>
        <p>
            Username: {{ object.username }}
        </p>
        <p>
            Full name: {{ object.first_name }} {{ object.last_name }}
        </p>
        <p>
            User since: {{ object.created_on|timezone:'Europe/Sofia' }}
        </p>
        <p>
            Description about {{ object.first_name }}:
            {{ object.profile_bio }}
        </p>

        <p>
            Email: {{ object.email }}
        </p>

        <div>
            {% if object.phonenumbersusermodel_set.count != 0 %}
                 <a>Contact me via phone</a>
                    <ul>
                        {% for phone in object.phonenumbersusermodel_set.all %}
                            <p>
                                {{ phone.phone }}
                            </p>
                        {% endfor %}
                    </ul>
            {% endif %}
        </div>

    {% if request.user.id == object.id %}
        <p>
            <a href="{% url 'contacts_profile' pk=object.pk %}">Add contacts</a>
        </p>
        <p>
            <a href="{% url 'edit_profile' pk=object.pk %}">Edit</a>
        </p>
    {% else %}
    {% endif %}

    </div>
    <h2>Products:</h2>
    <div class="tools">
        <div class="statuses">

            {% for tool in object.tool_set.all %}
                <ul>
                    <li>
                        <div class="image-container">
                            <a href="{%  url 'details_tool' tool.user tool.slug %}">
                                <img src="{{ tool.tool_photo }}" alt="The photo for this tool can't be accessed right now.">
                            </a>
                        </div>

                        <div>Product: {{ tool.name }}</div>
                        <div>Price: {{ tool.tool_price }} €</div>
                        <div>Location: {{ tool.tool_city }}, {{ tool.tool_country }}</div>
                    </li>

                </ul>
            {% endfor %}

        </div>
    </div>

</form>

</body>
</html>

{% endblock %}

templates/accounts/profile/edit_profile.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Profile edit</h1>

<form action="{% url 'edit_profile' object.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button>Submit changes</button>
        or
        <a href="{% url 'delete_profile' object.pk %}">Delete profile</a>
    </div>
</form>

</body>
</html>

templates/accounts/profile/profile_contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Contacts</h1>

<form action="{% url 'profile_contacts' user.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>Submit</button>
</form>

</body>
</html>

templates/accounts/profile/profile_delete.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Profile delete</h1>

<form action="{% url 'profile_delete' object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <h1>
        Are you sure you want to delete your profile?
        Any changes are irreversible.
    </h1>

    <button>Delete profile</button>
</form>

</body>
</html>

templates/accounts/profile/profile_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/styles/pic_size.css">
    <title>Document</title>
</head>
<body>

<h1>Profile details</h1>

<form action="{% url 'profile_details' pk=object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <div>
        <p>
            Username: {{ object.username }}
        </p>
        <p>
            Full name: {{ object.first_name }} {{ object.last_name }}
        </p>
        <p>
            Description about {{ object.first_name }}:
            {{ object.profile_bio }}
        </p>

        <p>
            Email: {{ object.email }}
        </p>

        <div>
            {% if object.phonenumbersusermodel_set.count != 0 %}
                 <a>Contact me via phone</a>
                    <ul>
                        {% for phone in object.phonenumbersusermodel_set.all %}
                            <p>
                                {{ phone.phone }}
                            </p>
                        {% endfor %}
                    </ul>
            {% endif %}
        </div>

    {% if request.user.id == object.id %}
        <p>
            <a href="{% url 'profile_contacts' pk=object.pk %}">Add contacts</a>
        </p>
        <p>
            <a href="{% url 'profile_edit' pk=object.pk %}">edit</a>
        </p>
    {% else %}
    {% endif %}

    </div>
    <h2>Products:</h2>
    <div class="tools">
        <div class="statuses">

            {% for tool in object.tool_set.all %}
                <ul>
                    <li>
                        <div class="image-container">
                            <a href="{%  url 'details_tool' tool.user tool.slug %}">
                                <img src="{{ tool.tool_photo }}" alt="The photo for this tool can't be accessed right now.">
                            </a>
                        </div>

                        <div>Product: {{ tool.name }}</div>
                        <div>Price: {{ tool.tool_price }} €</div>
                        <div>Location: {{ tool.tool_city }}, {{ tool.tool_country }}</div>
                    </li>

                </ul>
            {% endfor %}

        </div>
    </div>

</form>

</body>
</html>

{% endblock %}

templates/accounts/profile/profile_edit.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Profile edit</h1>

<form action="{% url 'profile_edit' object.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button>Submit changes</button>
        or
        <a href="{% url 'profile_delete' object.pk %}">Delete profile</a>
    </div>
</form>

</body>
</html>